
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sc
spec:
  hosts:
  - sc
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 2s
    route:
    - destination:
        host: sc
        subset: v1
