kind: Service
apiVersion: v1
metadata:
  name: sc0
  labels:
    app: sc0
spec:
  type: ClusterIP
  selector:
    app: sc-0
  ports:
  - name: http
    port: 8080
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    'consul.hashicorp.com/service-name': ic
    'consul.hashicorp.com/service-port': 'http'
    'consul.hashicorp.com/service-tags': 'version,v1'
  name: ic
  labels:
    app: ic
spec:
  type: ClusterIP
  selector:
    app: ic
  ports:
  - name: http
    port: 8080
